install: brew install hugo

branches:
  only:
    source

matrix:
  include:
    - os: osx

script:
  # print the version so if someone runs into trouble, its easier to debug
  - hugo version;
  # generate the site
  - hugo;

after_success:
  # deploy if we are on source and its not a PR
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && bash deploy.sh
